# Generated by Django 5.2.4 on 2025-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=models.TextField(editable=False),
        ),
    ]
