# Generated by Django 5.2.4 on 2025-07-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_tag_remove_quote_category_quote_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
