# Generated by Django 5.2.4 on 2025-07-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_quote_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=models.TextField(),
        ),
    ]
